# This file provides instructions for packaging.

`HTML-Zoom-Parser-HH5P`
	perl_version_from m`HTML::Zoom::Parser::HH5P`;
	version_from      m`HTML::Zoom::Parser::HH5P`;
	readme_from       m`HTML::Zoom::Parser::HH5P`;
	test_requires     p`Test::More 0.61` ;
	.

